name: Cloudbase-Init build  MSI

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019
    strategy:
      max-parallel: 100
      matrix:
        cbsinit_repo: ['https://github.com/ader1990/cloudbase-init-1']
        cbsinit_branch: ['wait_for_network_adapters']

    steps:
    - uses: actions/checkout@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build msi
      shell: cmd
      run: 
        powershell.exe .\BuildAutomation\BuildCloudbaseInitSetup.ps1^
            -ClonePullInstallerRepo:$false -CreateZip:$false ^ 
            -SetVCEnvVars:$true -RelativePythonDirPath:$true ^
            -CloudbaseInitRepoUrl ${{ matrix.cbsinit_repo }} -CloudbaseInitRepoBranch ${{ matrix.cbsinit_branch }}
    - uses: actions/upload-artifact@v1
      with:
        name: "CloudbaseInit_x64_MSI_${{ matrix.cbsinit_branch }}"
        path: 'CloudbaseInitSetup/bin/release/x64/CloudbaseInitSetup.msi'
